name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Deploy to Cloud run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v0
      with:
        image: gcr.io/cloudrun/hello
        service: hello-cloud-run
        credentials: ${{ secrets.GCP_SA_KEY }}

    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}